config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, :controllers => {:registrations => "registrations
  devise_for :users
  # resources :parties
  # resources :issues
  # resources :party_opinions, only: [:index, :create, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#index'

  get 'parties' => 'parties#index', as: :parties
  get 'party' => 'parties#show', as: :party
  get 'parties/filter' => 'parties#filter', as: :parties_filter

  get 'quizz' => 'pages#quizz', as: :quizz
  patch 'quizz/submit' => 'pages#submit_quizz', as: :submit_quizz
  get 'results' => 'pages#results', as: :results

  # post 'user-opinions' => 'user_opinions#create', as: :user_opinions
  patch 'user-opinions/:id/toggle' => 'user_opinions#toggle_is_interested_in', as: :user_opinions_toggle
  patch 'user_opinions/:id/stance-true' => 'user_opinions#set_stance_to_true', as: :user_opinions_stance_true
  patch 'user_opinions/:id/stance-false' => 'user_opinions#set_stance_to_false', as: :user_opinions_stance_false
  # post 'party-opinions' => 'issues#create'
end

app/models/party.rb
class Party < ApplicationRecord
  has_many :party_opinions, dependent: :destroy
  has_many :issues, through: :party_opinions
  has_many :scores, dependent: :destroy
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  def index
    @parties = Party.all
  end

  def show
    @parties = Party.find(params[:id])
  end

  def filter
    @parties = params[:party] == 'all' ? Party.all : Party.where(id: params[:party])

    respond_to do |format|
      format.html { redirect_to parties_path }
      format.js { render 'filter.js.erb' }
    end
  end
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/parties/_form.html.erb
<%= form_with(model: party, local: true) do |form| %>
  <% if party.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(party.errors.count, "error") %> prohibited this party from being saved:</h2>

      <ul>
      <% party.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parties/_party_details.html.erb
<% parties.each do |party| %>
  <div class="party-info">
      <h2><%= party.name %></h2>

      <% party.party_opinions.each do |party_opinion| %>
        <li>
          <strong><%= party_opinion.issue.name %>:</strong>
          <%= party_opinion.details %>
        </li>
      <% end %>
      <hr>
  </div>

  <% unless parties.index(party) == parties.length - 1 %>
    <hr>
  <% end %>
<% end %>

app/views/parties/edit.html.erb
<h1>Editing Party</h1>

<%= render 'form', party: @party %>

<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

app/views/parties/filter.js.erb
var filterPartyInfo = (infoHTML) => {
  const infoDiv = document.querySelector('#parties-info')
  infoDiv.innerHTML = infoHTML;
}

filterPartyInfo('<%= j render "party_details", parties: @parties %>');

app/views/parties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Where do the parties stand?</h1>
<hr>


<%= form_tag 'parties/filter', method: :get, remote: true, class: "form-inline" do |form| %>
  <div class="form-group">
    <select name="party" class="form-control">
      <option value="all">All</option>
      <%= @parties.each do |party| %>
        <option value="<%= party.id %>"><%= party.name %></option>
      <% end %>
    </select>

  </div>

  <%= submit_tag "Filter", class: "btn btn-primary" %>

<% end %>

<div id="parties-info" class="mt-5">

    <%= render 'party_details', parties: @parties  %>

</div>

app/views/parties/new.html.erb
<h1>New Party</h1>

<%= render 'form', party: @party %>

<%= link_to 'Back', parties_path %>

app/views/parties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @party.name %>
</p>

<%= link_to 'Edit', edit_party_path(@party) %> |
<%= link_to 'Back', parties_path %>