config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, :controllers => {:registrations => "registrations
  devise_for :users
  # resources :parties
  # resources :issues
  # resources :party_opinions, only: [:index, :create, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#index'

  get 'parties' => 'parties#index', as: :parties
  get 'party' => 'parties#show', as: :party
  get 'parties/filter' => 'parties#filter', as: :parties_filter

  get 'quizz' => 'pages#quizz', as: :quizz
  patch 'quizz/submit' => 'pages#submit_quizz', as: :submit_quizz
  get 'results' => 'pages#results', as: :results

  # post 'user-opinions' => 'user_opinions#create', as: :user_opinions
  patch 'user-opinions/:id/toggle' => 'user_opinions#toggle_is_interested_in', as: :user_opinions_toggle
  patch 'user_opinions/:id/stance-true' => 'user_opinions#set_stance_to_true', as: :user_opinions_stance_true
  patch 'user_opinions/:id/stance-false' => 'user_opinions#set_stance_to_false', as: :user_opinions_stance_false
  # post 'party-opinions' => 'issues#create'
end

app/views/pages/index.html.erb
<h1>Welcome, <%= current_user.username  %>!</h1>

<h3>Which issues matter to you?</h3>

<div class="user-issues d-flex flex-wrap">
  <% @user_opinions.each do |user_opinion| %>
    <div data-user-opinion-id="<%= user_opinion.id %>" class="mt-5 mb-5">
      <% if user_opinion.is_interested_in %>
        <%= link_to user_opinions_toggle_path(user_opinion), method: 'patch', remote: true, class: "button-answer mx-3 selected" do %>
          <%= user_opinion.issue.name %>
        <% end %>
      <% else %>
        <%= link_to user_opinions_toggle_path(user_opinion), method: 'patch', remote: true, class: "button-answer mx-3" do %>
          <%= user_opinion.issue.name %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

<div class="quizz-div">
  <h4><%= link_to "Go to the quiz!", quizz_path, class: "btn btn-primary btn-lg" %></h4>
</div>

<div class="party-stands-div">
  <%= link_to "Find out where your party stands", parties_path %>
</div>




<script src="" type="text/javascript"></script>

app/views/pages/quizz.html.erb
<style>
@import url('https://fonts.googleapis.com/css?family=DM+Serif+Display&display=swap');
</style>

<div class="banner-quizz">
  <div class="title-quizz">
  <h1>Find out which party<br> is right for you!</h1>
  </div>
</div>


<div class="flexbox-quizz">
  <% @user_opinions.each do |user_opinion| %>
    <li class="quizz-flexbox" data-user-opinion-id="<%= user_opinion.id %>">
      <div class="text-center">
        <div>
          <h2><%= user_opinion.issue.name %></h2>
        </div>
        <div>
          <%= user_opinion.issue.question %>
        </div>
      </div>

      <div class="d-flex justify-content-center align-items-center mt-3">
        <% if user_opinion.stance %>
          <%= link_to user_opinions_stance_false_path(user_opinion), method: 'patch', remote: true, class: "button-answer mx-3 button-false" do %>
             Disagree
          <% end %>

          <%= link_to user_opinions_stance_true_path(user_opinion), method: 'patch', remote: true, class: "button-answer selected mx-3 button-true" do %>

              I Agree
          <% end %>
        <% else %>
          <%= link_to user_opinions_stance_false_path(user_opinion), method: 'patch', remote: true, class: "button-answer mx-3 button-false selected" do %>
              Disagree
          <% end %>

          <%= link_to user_opinions_stance_true_path(user_opinion), method: 'patch', remote: true, class: "button-answer mx-3 button-true" do %>
              Agree
          <% end %>
        <% end %>
      </div>
    </li>
  <% end %>



</div>

<div class="text-center pb-5">
  <%= link_to submit_quizz_path, method: 'patch', class: "btn btn-primary btn-lg" do %>
    Submit Answers
  <% end %>

</div>

app/views/pages/results.html.erb
<div class="container py-3">
  <!-- <h1 class="mb-5">Your Results: See which party most aligns with your beliefs</h1> -->

  <div class="text-center">
    <%= image_tag("piechart", class: "pie-chart") %>
  </div>

  <%# @scores.each do |score| %>
    <!-- <p><strong><%#= score.party.name %></strong>: <%#= score.score %> matching answers</p> -->
  <%# end %>

  <% @user_opinions.each do |user_opinion| %>
    <li>
      <h2 class="text-center">
        <%= user_opinion.issue.name %>
      </h2>

      <h5 class="mt-3">Question: <%= user_opinion.issue.question %></h5>

      <div class="your-answer">Your Answer:
        <% if user_opinion.stance %>
          <span class="user-stance">I Agree</span>
        <% else %>
          <span class="user-stance">I Disagree</span>
        <% end %>

      </div>

      <div class="mt-3">
        <% @parties.each do |party| %>
          <% if party.party_opinions.find_by(issue: user_opinion.issue).stance == user_opinion.stance %>
            <div class="party-stance match">
              <i class="far fa-check-circle"></i>
          <% else %>
            <div class="party-stance not-match">
              <i class="far fa-times-circle"></i>
          <% end %>

              <strong><%= party.name %>: </strong>
              <% if party.party_opinions.find_by(issue: user_opinion.issue).stance %>
                  <span class="user-stance">Agree</span>
              <% else %>
                <span class="user-stance">Disagree</span>
              <% end %>
            </div>
          <!-- </div> -->
        <% end %>

      </div>


    </li>

    <hr>
  <% end %>

</div>